# Generated by Django 3.1.2 on 2020-10-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldi', '0002_auto_20201016_1612'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemhistory',
            table='aldi_item_history',
        ),
    ]
