# Generated by Django 3.2.2 on 2021-05-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldi', '0003_auto_20201016_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items', to='aldi.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='aldi.uom', verbose_name='unit of measurement'),
        ),
    ]
