# Generated by Django 3.2.2 on 2021-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldi', '0004_auto_20210507_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
