# Generated by Django 3.2.7 on 2023-03-23 16:04

import aldi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldi', '0005_alter_category_datetime_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items', to='aldi.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pack_qty',
            field=models.DecimalField(decimal_places=4, max_digits=20, validators=[aldi.models.Item.validate_value_not_negative]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[aldi.models.Item.validate_value_not_negative]),
        ),
    ]
